name: parse_issue
on:
  issues:
    types: [labeled]

env:
  ISSUE_TITLE: ${{ github.event.issue.title }}
  ISSUE_BODY: ${{ github.event.issue.body }}
  RECIPE_TITLE: $(echo "${{ github.event.issue.body }}" | awk '$0=="### Title of Recipe"{getline; getline; print}')
  
jobs:
  display_issue_info:
    if: ${{ github.event.label.name == 'approved' }}
    runs-on: ubuntu-latest

    steps:
    - name: Output submission details
      run: |
        echo "Submission title: ${{ env.ISSUE_TITLE }}"
        echo "Recipe title: ${{ env.ISSUE_TITLE }}"
        echo "Issue body: ${{ env.ISSUE_BODY }}"
    
    - name: Create file from issue body
      run: |
        #filename="$(echo -e "${filename}" | tr -d '[:space:]')"
        filename="${{ env.RECIPE_TITLE }}"
        echo "${filename}"
        echo "${filename,,}"
