name: parse_issue
on:
  issues:
    types: [labeled]

env:
  ISSUE_TITLE: ${{ github.event.issue.title }}
  ISSUE_BODY: ${{ github.event.issue.body }}
  
jobs:
  display_issue_info:
    if: ${{ github.event.label.name == 'approved' }}
    runs-on: ubuntu-latest
    steps:
    - name: Output submission details
      run: |
        echo "Submission title: ${{ env.ISSUE_TITLE }}"
        echo "Issue body: ${{ env.ISSUE_BODY }}"
    
    - name: Create file from issue body
      run: |
        recipename=$(echo "${{ env.ISSUE_BODY }}" | awk '$0=="### Title of Recipe"{getline; getline; print}')        
        recipename="$(echo -e "${recipename,,}" | tr -d '[:space:]')"
        mkdir -p "submissions/${recipename}/images"
        touch "submissions/${recipename}/images/.placeholder"
        echo "${{ env.ISSUE_BODY }}" > "submissions/${recipename}/${recipename}.raw"

    - uses: actions/checkout@v3
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Check if there are any changes
      id: verify_diff
      run: |
        git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
    - name: Commit submitted recipe additions
      run: |
        git add submissions/*
        git commit -a -m "Created raw recipe submission for $(echo "${{ env.ISSUE_BODY }}" | awk '$0=="### Title of Recipe"{getline; getline; print}')"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
  