name: parse_issue
on:
  issues:
    types: [labeled]

env:
  ISSUE_TITLE: ${{ github.event.issue.title }}
  ISSUE_BODY: ${{ github.event.issue.body }}
  RECIPE_TITLE: $(echo "${{ github.event.issue.body }}" | awk '$0=="### Title of Recipe"{getline; getline; print}')
  
jobs:
  display_issue_info:
    if: ${{ github.event.label.name == 'approved' }}
    runs-on: ubuntu-latest

    steps:
    - name: Output submission title
      run: echo "${{ env.ISSUE_TITLE }}"

    - name: Output recipe body
      run: echo "${{ env.ISSUE_BODY }}"
    
    - name: Create file from issue body
      run: |
        #lowercase & no spaces
        filename="$(echo "${{ env.RECIPE_TITLE }}" | awk '{print tolower($0)}')"
        #filename="$(echo -e "${filename}" | tr -d '[:space:]')"
        echo -e "${filename}"
        echo "${{ env.RECIPE_TITLE }}" | awk '{print tolower($0)}'
