name: parse_issue
on:
  issues:
    types: [labeled]

env:
  ISSUE_TITLE: ${{ github.event.issue.title }}
  ISSUE_BODY: ${{ github.event.issue.body }}
  
jobs:
  display_issue_info:
    if: ${{ github.event.label.name == 'approved' }}
    runs-on: ubuntu-latest
    steps:
    - name: Output submission details
      run: |
        echo "Submission title: ${{ env.ISSUE_TITLE }}"
        echo "Issue body: ${{ env.ISSUE_BODY }}"
    
    - name: Create file from issue body
      run: |
        recipename=$(echo "${{ env.ISSUE_BODY }}" | awk '$0=="### Title of Recipe"{getline; getline; print}')        
        recipename="$(echo -e "${recipename,,}" | tr -d '[:space:]')"
        mkdir -p "./submissions/${recipename}/images"
        echo "${{ env.ISSUE_BODY }}" > "./submissions/${recipename}/${recipename}.raw"
#    - name: Commit submitted recipe changes
#      if: steps.verify_diff2.outputs.changed == 'true'
#      run: |
#        git add submissions/*
#        git commit -a -m "Created raw recipe submission for $(echo "${{ env.ISSUE_BODY }}" | awk '$0=="### Title of Recipe"{getline; getline; print}')"
#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        branch: ${{ github.head_ref }}
