name: parse_submission

on:
  issues:
    types: [labeled]
  
env:
  ISSUE_TITLE: ${{ github.event.issue.title }}
  ISSUE_BODY: ${{ github.event.issue.body }}

jobs:
  build:
    if: ${{ github.event.label.name == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Call python issue submission parser
        run: python scripts/parse_submission.py "${{ env.ISSUE_BODY }}"
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Add new submissions to git
        run: |
          git add submissions
          git add recipes
      - name: Commit markdown changes
        run: |
          git commit -a -m "Processed new recipe from submitted issue template"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
