name: parse_issue
on:
  issues:
    types: [labeled]

env:
  ISSUE_TITLE: ${{ github.event.issue.title }}
  ISSUE_BODY: ${{ github.event.issue.body }}
  
jobs:
  display_issue_info:
    if: ${{ github.event.label.name == 'approved' }}
    runs-on: ubuntu-latest

    steps:
    - name: Output submission title
      run: echo "${{ env.ISSUE_TITLE }}"

    - name: Output recipe body
      run: echo "${{ env.ISSUE_BODY }}"
    
    - name: Output recipe title
      run: |
        title=$(echo "${{ env.ISSUE_BODY }}" | awk '$0=="### Title of Recipe"{getline; getline; print}')
        #echo "RECIPE_TITLE=$title" >> "$GITHUB_ENV"
        echo "local: $title"
    - name: access recipe title
      run: |
        echo "accessing: $title"
