name: Rebuild Markdown Files [bot]

on:
  push:
    branches: [ "main" ]
    paths:
      - recipes/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: install dependencies
        run: pip install loguru
      - name: Rebuild markdown recipes
        run: python scripts/generate_markdown_recipes.py
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "action@github.com"
      - name: Check if there are any changes
        id: verify_diff1
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit markdown changes
        if: steps.verify_diff1.outputs.changed == 'true'
        run: |
          git add recipes/*.md
          git commit -a -m "Recreated recipes from stubs"
      - name: Recreate README.md TOC
        run: python scripts/update_readme.py
      - name: Check if there are any changes
        id: verify_diff2
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit TOC changes
        if: steps.verify_diff2.outputs.changed == 'true'
        run: |
          git add README.md
          git add tags/*
          git commit -a -m "Regenerated README.md TOC"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
