name: update-recipes

on:
  push:
    branches: [ "main" ]
    paths:
      - recipes/**
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - name: install dependencies
        run: pip install loguru
      - name: Rebuild markdown recipes
        run: python scripts/generate_markdown_recipes.py
      - name: Commit markdown changes
        run: |
          git config --global user.email "fexofenadine@users.noreply.github.com"
          git config --global user.name "fexofenadine"
          git add recipes/*.md
          git commit -a -m "Recreated recipes from stubs"
      - name: Push markdown changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - name: Recreate README.md TOC
        run: python scripts/update_readme.py
      - name: Commit TOC changes
        run: |
          git config --global user.email "fexofenadine@users.noreply.github.com"
          git config --global user.name "fexofenadine"
          git add README.md
          git add tags/*
          git commit -a -m "Regenerated README.md TOC"
      - name: Push TOC changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
